import {
  CASE_DELAY_REASON,
  DELAY_REASON,
  FILTERED_USERS_TO_SEND_SMS,
  NOTIFICATION,
  TIMELOG,
  TIMER,
  VOICE_NOTE,
} from './CommonTypes';

export type TIMELOG_RESPONSE = Array<TIMELOG>;
export type GET_DELAY_REASON_RESPONSE = Array<DELAY_REASON>;
export type GET_CASE_DELAY_REASON_RESPONSE = Array<CASE_DELAY_REASON>;
export type GET_VOICE_NOTES_LIST_RESPONSE = Array<VOICE_NOTE>;
export type GET_TIMERS_LIST_RESPONSE = Array<TIMER>;

export type FILTER_USERS_TO_SEND_SMS_RESPONSE = {
  response: FILTERED_USERS_TO_SEND_SMS;
};

export type GET_NOTIFICATIONS_LIST_RESPONSE = Array<NOTIFICATION>;
