import {API_STATUS} from 'src/Utils/Types';
import {
  ACTIVE_CASE,
  ANESTHELOGIST,
  CASE_DETAIL,
  CASE_SUBMITTED,
  MILESTONE_REVISION,
  NOTIFICATION_PREF,
  OPTIONAL_MILESTONE_REVISION,
  OT_ROOM,
  PROCEDURE,
  SURGEON,
  USER_ROLE_DEPT_MAPPING,
} from './CommonTypes';
import {USER} from '@modules/AuthModule/Types/CommonTypes';

export type OTS_LIST_RESPONSE = Array<OT_ROOM>;

export type SWICTH_CASE_SELECTION_RESPONSE = {
  message: string;
  status: API_STATUS;
};

export type GET_CASE_BY_OTS_RESPONSE = Array<CASE_DETAIL>;
export type GET_SUBMITTED_CASES_RESPONSE = Array<CASE_SUBMITTED>;

export type GET_ACTIVE_CASES_LIST_RESPONSE = Array<ACTIVE_CASE>;
export type GET_PROCEDURE_LIST_RESPONSE = Array<PROCEDURE>;
export type GET_SURGEON_ANESTHESIOLOGIST_LIST_RESPONSE = Array<
  SURGEON | ANESTHELOGIST
>;
export type GET_MILESTONE_REVISION_RESPONSE = Array<MILESTONE_REVISION>;
export type GET_OPTIONAL_MILESTONES_RESPONSE =
  Array<OPTIONAL_MILESTONE_REVISION>;

export type GET_NOTIFICATION_PREF_RESPONSE = NOTIFICATION_PREF;

export type GET_SURGEON_LIST_RESPONSE = Array<SURGEON>;
export type GET_AESTHELOGIST_LIST_RESPONSE = Array<ANESTHELOGIST>;
export type GET_USER_LIST_BY_ROLE_RESPONSE = Array<USER>;
export type GET_USER_LIST_BY_DEPARTMENT_RESPONSE = Array<USER>;
export type GET_ALL_USER_LIST_RESPONSE = Array<USER>;
export type GET_USER_ROLES_RESPONSE = Array<string>;
export type GET_USER_ROLE_DEPT_MAPPING_RESPONSE = Array<USER_ROLE_DEPT_MAPPING>;
